---
- name: Remove sites-avaiable and sites-enabled
  # file: 
  #   path: "{{ item }}"
  #   state: absent
  # with_items:
  #   - /etc/nginx/sites-available/*
  #   - /etc/nginx/sites-enabled/*
  shell: "rm -rf /etc/nginx/sites-available/* /etc/nginx/sites-enabled/*"
- name: Copy config file default 
  copy:
    src: default
    dest: /etc/nginx/sites-available/
- name: Copy config file php-info and hello-world
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: 
    - { src: php-info-domain.j2 , dest: /etc/nginx/sites-available/php-info }
    - { src: hello-world-domain.j2 , dest: /etc/nginx/sites-available/hello-world }
- name: Create link sites-available and sites-enabled
  shell: "ln -s /etc/nginx/sites-available/* /etc/nginx/sites-enabled/"
  ignore_errors: true
- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /var/www/html/php-info/
    - /var/www/html/hello-world/
- name: Copy web file
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: php-info.php , dest: /var/www/html/index.php }
    - { src: php-info.php , dest: /var/www/html/php-info/index.php }
    - { src: hello-world.html , dest: /var/www/html/hello-world/index.html }
  notify: 
    - validate nginx
    - restart nginx
