---
- hosts: "{{hostname}}"
  gather_facts: yes
  become: yes
#  pre_tasks:
#  - name: 'install python'
#    raw: sudo apt-get update && sudo apt-get -y install python3
#    tags: ['always']
  tasks:
  - name: "Check connection"
    ping:
    tags: ['ping']
  - name: "Echo user" 
    command: "whoami"
    become: yes
    tags:
    - check_user

  - name: "Create dir"
    file:
      path: "{{item}}"
      state: absent
    with_items:
      - /var/www/html/demo01
      - /var/www/html/demo02
    ignore_errors: yes
